### ISSUE TITLE
Installing Doki-Theme Issue 

### ISSUE THREAD

**Issue by macDanielZ** [doki-theme/doki-theme-eclipse#5]
Hi, I'm the user that asks you about the Doki-theme install issue on Gmail, I'm posting more detailed information about my issue here.

I've been trying to install following the instruction on README.MD, open > help > install new software > put the link. But it still has the same issue 
![image](https://user-images.githubusercontent.com/95349667/144695201-e67fefed-b9a5-48fa-aff6-7fb939de1a87.png)

Before I'm installing I've got a notification like this and some trust-issue notification.
![image](https://user-images.githubusercontent.com/95349667/144695383-97dc56d3-65b3-458d-9326-8f6d2ca29f66.png)
![image](https://user-images.githubusercontent.com/95349667/144695418-583205a3-f898-45a3-acac-85dcabb7b3e0.png)
I check the box and I select Trust Selected then it's installed but got the problem as above.

I've tried to put Asset Directory Preferences on Doki-Theme Setting using this folder 
![image](https://user-images.githubusercontent.com/95349667/144695246-00ba846c-5cab-4828-b44d-1c2c2d5d9a0b.png)
( I've been unzipped it )

Thank you for helping me.

**Comment by Unthrottled** [comment]
Thank you for providing more information! 

You are using Eclipse 2021-09 (4.21.0). 

Could you answer a few questions for me, please?

- What operating system are you using? (Windows 10?)
- Could you provide the error logs? `Help -> About Eclipse -> Installation Details -> Configuration -> View Error Log`

https://user-images.githubusercontent.com/15972415/144713197-0cb3c1a8-8728-4c90-a0a1-c2e66b417cc3.mp4

**Comment by macDanielZ** [comment]
Yes I'm using windows 10

for the error log :
[error_log.txt](https://github.com/doki-theme/doki-theme-eclipse/files/7654403/error_log.txt)

**Comment by Unthrottled** [comment]
@macDanielZ Thank you for the supporting information. I believe I have addressed the issue. I've published the [v0.10.1](https://github.com/doki-theme/doki-theme-eclipse/releases/tag/v0.10.1) to the plugin update site, so you should be able to go to `Help -> Check for Updates` and the Doki Theme should be part of the list. 

If the issue isn't fixed, feel free to re-open the issue, and post the latest error log please, thanks!
