### ISSUE TITLE
Eclipse Doki Sticker Black Box

### ISSUE THREAD

**Issue by DVecc** [doki-theme/doki-theme-eclipse#7]
Hi, I'm having an issue with the Eclipse version of the plugin:
Version: 2021-09 (4.21.0)
Build id: 20210910-1417

No matter which sticker I use or theme I change to the sticker window always has this black box next to the sticker.
![image](https://user-images.githubusercontent.com/21961826/151282358-be441362-afd0-43d2-b177-3d1fa81b98d6.png)

**Comment by Unthrottled** [comment]
Got it! I'll look into this issue some time in the near future, thanks for reporting an your patience.

**Comment by Unthrottled** [comment]
I am currently not able to reproduce the issue on Ubuntu 20.04.3 LTS

```
Version: 2021-09 (4.21.0)
Build id: 20210910-1417
```

Are you using any custom themes or are you on a different operating system?

![Screenshot from 2022-02-07 17-28-31](https://user-images.githubusercontent.com/15972415/152889991-fb816faa-2375-4eed-bdc7-fa0924c83a90.png)

**Comment by DVecc** [comment]
The OS I'm experiencing the issue on is Windows 11.

The only theme I was using was the Darkest Dark plugin that is linked in your repository. Even after uninstalling the Darkest Dark plugin as it was causing issues with my right-click context menu and using a new workspace the issue remains for me with the default themes that are bundled with eclipse. 


![image](https://user-images.githubusercontent.com/21961826/152890573-340bebf9-c030-4ff2-8091-84f529cc82a9.png)
![image](https://user-images.githubusercontent.com/21961826/152890620-235c6f33-b671-475e-b638-5703bd65defd.png)

**Comment by DVecc** [comment]
I should note that this is only occurring when using a dark theme, I just swapped to the default light theme to check if the issue was occurring with it enabled as well and everything appears normal. 
![image](https://user-images.githubusercontent.com/21961826/152891206-6845148a-fc0d-48bc-ad61-ed137b1f0699.png)

**Comment by Unthrottled** [comment]
Thanks for supplying this supporting information! I'll switch over to my windows machine soon. I'm starting to remember I had to do dumb stuff to get the sticker to float to the left (I think). So that is where that box may be coming from. Will look into it, thanks!

**Comment by Unthrottled** [comment]
Alright, I've got it figured out. I was able to replicate & fix the issue

![image](https://user-images.githubusercontent.com/15972415/153094994-ace8359a-23ae-4438-8e72-02c64572a974.png)

I'll have a release out shortly.

**Comment by Unthrottled** [comment]
Aight, v74.1.1 should be available, if you check for updates. Let me know if you have any issues after installation.

**Comment by DVecc** [comment]
Updated and everything is working as expected!
![image](https://user-images.githubusercontent.com/21961826/153097747-7288e833-8760-4560-b999-a82d30046d4b.png)
