### ISSUE TITLE
Error Installing the theme

### ISSUE THREAD

**Issue by CalebThePerson** [doki-theme/doki-theme-eclipse#8]
I get this error message when trying to install the theme and I can't exactly tell if it's a me problem or a package problem.

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: Doki-Theme-Eclipse 88.1.1 (io.unthrottled.doki.theme.eclipse.feature.group 88.1.1)
  Missing requirement: Doki-theme-eclipse 88.1.1 (doki-theme-eclipse 88.1.1) requires 'osgi.bundle; org.apache.commons.httpclient 3.1.0' but it could not be found
  Cannot satisfy dependency:
    From: Doki-Theme-Eclipse 88.1.1 (io.unthrottled.doki.theme.eclipse.feature.group 88.1.1)
    To: org.eclipse.equinox.p2.iu; doki-theme-eclipse [88.1.1,88.1.1]
```

**Comment by Unthrottled** [comment]
Huh, I wonder if the newer version of eclipse doesn't have `org.apache.commons.httpclient 3.1.0` bundled in it.

What version of eclipse are you using and on what OS?

**Comment by CalebThePerson** [comment]
```
Version: 2022-09 (4.25.0)
OS: MacOS (11.6.5 Big Sur)
```
Is there any way to install this myself LOL.  Or maybe i should just downgrade eclipse ?

**Comment by Unthrottled** [comment]
> Is there any way to install this myself LOL.

Yeah, I think there might be a manual work around. 

- [Download the Doki Theme jar from the release](https://github.com/doki-theme/doki-theme-eclipse/releases/tag/v88.1-0.1.1)
- [Download the jar with http client](https://mvnrepository.com/artifact/commons-httpclient/commons-httpclient/3.1)
- [Drop both jars in the dropins directory](https://stackoverflow.com/questions/55693896/where-is-eclipse-dropins-folder)

That might work. I might have time this weekend to see if  that works.

> Or maybe i should just downgrade eclipse ?

Or you could [upgrade to Intellij Community](https://www.jetbrains.com/idea/download/#section=mac). 💯 
My [JetBrains Theme Plugin](https://github.com/doki-theme/doki-theme-jetbrains#the-doki-theme-jetbrains-ides) is a bajillion times better.

**Comment by CalebThePerson** [comment]
I bet it is, but my class requires me to use Eclipse sadly.  I'll try the manual way as well this weekend.

**Comment by CalebThePerson** [comment]
Update: I dropped both jars in the dropins directory.  And I'm pretty sure it did not work. I do not see any extra themes in the editor theme tab.

**Comment by Unthrottled** [comment]
This plugin doesn't provide any themes, just a sticker view. [See the settings docs for more info](https://github.com/doki-theme/doki-theme-eclipse#settings)

I tried to figure out how to provide a theme, but there isn't any good documentation and I die inside every-time I have to use Eclipse.

**Comment by CalebThePerson** [comment]
I don't see the doki theme tab in the preferences.  I'm assuming this method doesn't work, sadge

**Comment by Unthrottled** [comment]
Bummer, well I'll add this to my list of things todo.

**Comment by Noogii** [comment]
Any news on the fix?

**Comment by Unthrottled** [comment]
It's still borked, haven't taken the time to investigate the dependency management for eclipse plugins yet.

**Comment by Unthrottled** [comment]
Anybody is free to take a look, (been putting of installing eclipse on my macbook), so I'd have to reproduce on my windows/linux machine.

**Comment by Unthrottled** [comment]
Finally got around to fixing the issue. It cost me some if my life span, but it works now!
